### ISSUE TITLE
ValueError

### ISSUE THREAD

**Issue by Shaheer-Akun** [krishnaik06/Car-Price-Prediction#2]
Hi Sir,
Thanks for conducting Live session of End-to-End project implementation, It was very helpful in learning project implementation,
but I've been facing ValueError
**"ValueError: Number of features of the model must match the input. Model n_features is 9 and input n_features is 8"**
**File "/Users/shaheer/ML projects/app.py", line 46, in predict
prediction=model.predict([[Present_Price,Kms_Driven2,Owner,Year,Fuel_Type_Diesel,Fuel_Type_Petrol,Seller_Type_Individual,Transmission_Mannual]])**
kindly review this issue and suggest fix,

Thank you.

**Comment by antonyanto** [comment]
There is no such error has occurred if you don't touch or edit the main.py or app.py files in this repository. However if you have implemented this project by yourself, you might have trained your model with "Selling_Price" attribute or with any your feature engineered independent features or variables. So, double check your model's input shape and names of the attributes or independent features and give the correct features to model's prediction method to get the result and also don't forget to update if any in main.py and app.py .

**Comment by Shaheer-Akun** [comment]
@antonyanto 
Hi Anthony,
Thanks for reaching out, but issue seems to be different,
after onehot encoding **owner** feature we have Owner_1, Owner_3 features in our X_train, but in main.py there's only one Owner feature.

**Comment by antonyanto** [comment]
@Shaheer-Akun 
Hello Shaheer
The "Owner" feature in this dataset is already label encoded (i.e labels = 0,1,3). So there is no need to encode further.
If you are trying to encode "Owner" feature only with pandas get_dummies() method, you will get 3 columns specifying 3 categories (i.e 0,1,3) and also if you are doing so with scikit learn's OneHotEncoder, you will get the same.
But if you try to encode the "Owner" feature with other categorical features like "Fuel_Type" or "Seller_Type", you will get different output because pandas get_dummies() method consider this "Owner" feature as numerical data or Quantitative data. I hope you may be able to get what I'm coming to say that, the "Owner" feature used here don't want to be encoded once again as one-hot encoded because it is already encoded as labels (i.e 0,1,3). I hope this explanation helps you.

**Comment by Shaheer-Akun** [comment]
Double BAM! moment, kinda Josh Starmer says in his YouTube channel
Thanks a lot for clearing my foggy picture on onehotEncoding.

**Comment by Shaheer-Akun** [comment]
@antonyanto 
Double BAM! moment, kinda Josh Starmer says in his YouTube channel
Thanks a lot for clearing my foggy picture on onehotEncoding.
